resotoclient/__init__.py
TLS verification is now optional.
=> add optional TLS verification

pyproject.toml
=> bump the version to 0.1.5

pyproject.toml
=> bump 0.1.7

poetry.lock, pyproject.toml
=> [fix] Allow major version bump in cryptography

pyproject.toml, resotoclient/__init__.py, resotoclient/ca.py
Added a TLS refresh worker for resotoclient
=> Add a TLS refresh worker

pyproject.toml, resotoclient/ca.py
=> Update the JWT error message

pyproject.toml
=> [chore] bump version to 0.1.11

resotoclient/__init__.py, tests/resotoclient_test.py
=> [fix] Handle non latin characters correctly

pyproject.toml
Bump version to 0.1.13
- Fixes #XXXX
=> [bump] Bump version to 0.1.13

README.md, pyproject.toml
=> Bump 0.1.14

poetry.lock, pyproject.toml, resotoclient/__init__.py, tests/resotoclient_test.py
Adds support for aggregate search and flattens the datastructure unless specified otherwise. Returns the complete dataframe including ancestors, desired, metadata section.
=> Flatten json structure

.github/workflows/resotoclient_test_and_publish.yml, noxfile.py, poetry.lock, pyproject.toml, pytest.ini, resotoclient/__init__.py, resotoclient/ca.py, resotoclient/http_client/__init__.py, resotoclient/http_client/aiohttp_client.py, resotoclient/http_client/event_loop_thread.py, resotoclient/http_client/sync_client.py, tests/http_client/event_loop_thread_test.py, tests/resotoclient_test.py
Requests replaced with aiohttp
Missing: complete requests removal from the dependencies
=> [resotoclient][feat] Use aiohttp instead of requests

resotoclient/ca.py
This will avoid blocking in threads and
- Fixes #XXXX
=> [resotoclient][fix] Make the CA holder thread daemon

pyproject.toml
=> bump 1.0.1

pyproject.toml, resotoclient/__init__.py, resotoclient/http_client/__init__.py, resotoclient/http_client/aiohttp_client.py
Added a original response object in the HttpResponse class
- Fixes #XXXX
=> [resotoclient][feat] Add the response object to the HttpRespones

resotoclient/__init__.py, resotoclient/async_client.py, resotoclient/http_client/aiohttp_client.py, tests/async_resotoclient_test.py
Allow to send and receive events from Resoto.
=> [feat] Add websocket handler to listen to events

poetry.lock, pyproject.toml, resotoclient/__init__.py, resotoclient/async_client.py, resotoclient/ca.py
Fixed the multipart response handling and added the custom file certificate feature back.
=> [resotoclient][fix] Adjust the support for multipart handling

pyproject.toml
=> bump 1.1.1

resotoclient/async_client.py, resotoclient/http_client/aiohttp_client.py
=> [fix] Leave events generator if connection is lost

poetry.lock, pyproject.toml, resotoclient/json_utils.py, resotoclient/models.py, tests/async_resotoclient_test.py
- jsons tries to read date strings into datetime objects by default, which is wrong
- fix the model reading
=> [fix] Fix json handling and model reading

.editorconfig, .github/workflows/resotoclient_test_and_publish.yml, poetry.lock, pyproject.toml, resotoclient/__init__.py, resotoclient/async_client.py, resotoclient/http_client/aiohttp_client.py, tests/__init__.py, tests/async_resotoclient_test.py, tests/resotoclient_test.py
=> [feat] Allow propagating additional headers. Bump libraries and fix tests

pyproject.toml, resotoclient/__init__.py, resotoclient/async_client.py
=> fix: default value for optional psk

resotoclient/__init__.py, resotoclient/async_client.py, resotoclient/http_client/aiohttp_client.py, resotoclient/jwt_utils.py
Renew the authorization header before it expires.
=> feat: renew authorization header

poetry.lock, pyproject.toml, resotoclient/models.py
=> feat: add metadata to kinds and properties

poetry.lock, pyproject.toml, resotoclient/__init__.py, resotoclient/ca.py, resotoclient/http_client/aiohttp_client.py
=> feat: don't overact

pyproject.toml, resotoclient/__init__.py, resotoclient/async_client.py, resotoclient/json_utils.py, resotoclient/models.py, tests/async_resotoclient_test.py, tests/model_test.py
=> [fix] simplify json handling

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .github/dependabot.yml, .github/workflows/fixclient_test_and_publish.yml, fixclient/__init__.py, fixclient/async_client.py, tests/__init__.py, tests/fixclient_test.py
=> [feat] use fixcore
